# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: NetTree
subtitle: ''
description: ''
keywords:
author: Cyan Chau
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://Cyanzzy.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# 其中 xxxxxx 是前面多次用到的你的GitHub用户名
deploy:
  type: git
  repository: git@github.com:Cyanzzy/Cyanzzy.github.io.git
  branch: main

# 本地搜索
search:
  path: search.xml
  field: all
  content: true

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true #开关插件版看板娘
  scriptFrom: local #默认
  pluginRootPath: live2dw/ #插件在站点上的根目录(相对路径)pluginJsPath: lib/ #脚本文件相对与插件根目录路径
  pluginModelPath: assets/ #模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https:/ /npm.elemecdn. com/live2d-widget@3.x/lib/L2Dwidget.min.js #你的自定义 url
  tagMode: false #标签模式，是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false #调试,是否在控制台输出日志
  model:
  use: live2d-widget-model-koharu # npm-module package name#use: wanko #博客根目录/live2d_models/下的目录名
  # use: ./wives/wanko #相对于博客根目录的路径
  # use: https ://mpm.elemecd .com/live2d-widget-model-wanko@1.0.5/assets/wanko.model. json #你的自定义_url
  display:
    position: left #控制看板娘位置
    width: 150 #控制看板娘大小
    height: 300 #控制看板娘大小
  mobile:
    show: false #手机中是否展示  

#envelope_comment
#see https://akilar.top/posts/e2d3c450/
envelope_comment:
  enable: true #控制开关
  custom_pic:
    cover: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/violet.jpg #信笺头部图片
    line: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/line.png #信笺底部图片
    beforeimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/before.png # 信封前半部分
    afterimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/after.png #信封后半部分
  message: #信笺正文，多行文本，写法如下
    - 有什么想问的?
    - 有什么想说的?
    - 有什么想吐槽的?
    - 哪怕是有什么想吃的，都可以告诉我哦~
  bottom: 自动书记人偶竭诚为您服务! #仅支持单行文本
  height: #105epx，信封划出的高度
  path: #【可选】comments的路径名称。默认为 comments，生成的页面为 comments/index. html
  front_matter: #【可选】 comments页面的 front_matter配置
    title: Comments
    comments: true

#footer_beautify
#页脚计时器:[Native JS Timer](https : / /akilar.top/posts/b941af/)
#页脚徽标:[Add Github Badge](https: //akilar .top/posts/e87ad7f8/)
footer_beautify:
  enable:
    timer: true #计时器开关
    bdage: true #徽标开关
  priority: 5 #过滤器优先权
  enable_page: all #应用页面
  exclude: #屏蔽页面
    # - /posts/
  # - /about/
  layout: #挂载容器类型
    type: id
    name: footer-wrap
    index: 0
  # 计时器部分配置项（看你喜欢哪个，最好下载下来放到自己的项目中不然会增加我网站的负载)
  runtime_js : /js/runtime.js
  runtime_css: /css/runtime.min.css
  # 这是店长的
  # runtime_js: https://npm.elemecdn.com/hexo-butterfly-footer-beautify@1.0.0/1ib/runtime.js
  # runtime_css: https://npm.elemecdn.com/hexo-butterfly-footer-beautify@1.0.0/lib/runtime.css
  # # 徽标部分配置项
  swiperpara: 0 # 若非e，则开启轮播功能，每行徽标个数
  bdageitem:
    - link: https://hexo.io/ # 徽标指向网站链接
      shields: https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo #徽标API
      message: 博客框架为Hexo_v6.2.0  # 徽标提示语
    - link: https://butterfly.js.orgl
      shields: https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender
      message: 主题版本Butterfly_v4.3.1
  # 以下拥有域名再处理
    # - link: https://vercel.com/
    #   shields: https://img.shields.io/badge/Hosted-Vercel-brightgreen?style=flat&logo=Vercel
    #   message: 本站采用多线部署，主线路托管于Vercel
    # - link: https://dashboard.4everland.org/
    #     # https: / /img.shields.io/badge/Hosted-4EVERLAND-3FE2C1?style=flat&logo=IPFS
    #   shields: https://img.shields.io/badge/Hosted-4EVERLAND-22DDDD?style=flat&logo=IPFS
    #   message: 本站采用多线部署，备用线路托管于4EVERLAND
    - link: https://github.com/
      shields: https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub
      message: 本站项目由Github托管
    - link: http://creativecommons.org/licenses/by-nc-sa/4.0/
      shields: https://img.shields.io/badge/Copyright-BY--NC--SA8%204.0-d42328?style=flat&logo=Claris
      message: 本站采用知识共享署名-非商业性使用-相同方式共享4.0国际许可协议进行许可
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js
  swiperbdage_init_js: https://npm.elemecdn.com/hexo-butterfly-footer-beautify/1lib/swiperbdage_init.min.js

# hexo-butterfly-categories-card
# see https://akilar.top/posts/a9131002/
categoryBar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  column: odd # odd：3列 | even：4列
  row: 1 #显示行数，默认两行，超过行数切换为滚动显示
  message:
    - descr: # Language
      cover: https://cyan-images.oss-cn-shanghai.aliyuncs.com/images/categoryBar-cover1.png
    - descr: # Technology
      cover: https://cyan-images.oss-cn-shanghai.aliyuncs.com/images/categoryBar-cover2.png
    - descr: # Science
      cover: https://cyan-images.oss-cn-shanghai.aliyuncs.com/images/categoryBar-cover3.png
    - descr: # Algorithm
      cover: https://cyan-images.oss-cn-shanghai.aliyuncs.com/images/categoryBar-cover4.png
  custom_css: https://npm.elemecdn.com/hexo-butterfly-categories-card@1.0.0/lib/categorybar.css

magnet:
  enable: true
  priority: 1
  enable_page: /
  type: categories
  devide: 2
  display:
    - name: Language
      display_name: 编程语言
      icon: ❤
    - name: Technology
      display_name: 技术架构
      icon: 🧡  
    - name: Science
      display_name: 科学研究
      icon: 💛
    - name: Algorithm
      display_name: 编程算法
      icon: 💚
  color_setting:
    text_color: black
    text_hover_color: white
    background_color: "#F2F2F2"
    background_hover_color: "#3ecdf1"
  layout:
    type: id
    name: recent-posts
    index: 0
  custom_css: /css/custom.css  

  temple_html: '<div class="recent-post-item" style="width:100%;height:auto"><div id="catalog_magnet">${temple_html_item}</div></div>'  
  plus_style: ""

#hexo-butterfly-swiper
#see https: // akilar.top/posts/ 8e1264d1/
swiper:
  enable: true #开关
  priority: 5 #过滤器优先权
  enable_page: / #应用页面
  timemode: date #date/updated
  layout: # 挂载容器类型
    type: id      
    name: recent-posts
    index: 0
  default_descr: Articles
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper css依赖
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper js依赖
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css #适配主题样式补丁
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiper初始化方法

butterfly_article_double_row:
  enable: true


